import Head from "next/head";
import styles from "@/styles/Home.module.css";
import TodoList from "@/components/TodoList";
import { useState } from "react";

// Interface for TodoList
export interface ITodo {
  key: number;
  task: string;
  completed: boolean;
}

export default function Home() {
  // List of Todos
  const [todos, setTodos] = useState<ITodo[]>([
    { key: 1, task: "Clean", completed: false },
    { key: 2, task: "Eat", completed: false },
  ]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TodoList todos={todos} setTodos={setTodos} />
      </main>
    </>
  );
}
