import Head from "next/head";
import styles from "@/styles/Home.module.css";
import TodoList from "@/components/TodoList";
import { useState } from "react";
import { v4 as uuidv4 } from "uuid";

// Interface for TodoList
export interface ITodo {
  id: string;
  task: string;
  completed: boolean;
}

export default function Home() {
  // List of Todos
  const [todos, setTodos] = useState<ITodo[]>([
    { id: "1", task: "Clean", completed: false },
    { id: "2", task: "Eat", completed: false },
  ]);

  // New Todo Holder
  const [newTodo, setNewTodo] = useState<string>("");

  // Change newTodo value when input is changed
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setNewTodo(e.target.value);
  };

  // Handle adding of new todo
  const handleAdd = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const newId = uuidv4();
    const newTask = newTodo.trim();
    if (newTask) {
      const newTodoItem: ITodo = {
        id: newId,
        task: newTask,
        completed: false,
      };
      setTodos([...todos, newTodoItem]);
      setNewTodo("");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TodoList todos={todos} setTodos={setTodos} />
        <form onSubmit={handleAdd}>
          <input
            placeholder="Add New Todo"
            value={newTodo}
            onChange={handleInputChange}
          />
          <br />
          <button type="submit">Add</button>
        </form>
      </main>
    </>
  );
}
